// Reviews页面相关的类型定义

// Legacy types (keeping for backward compatibility)
export interface PostData {
  id: number;
  avatar: string;
  username: string;
  timestamp: string;
  text: string;
  image?: string;
  likes: number;
  comments: number;
}

export interface StudentPostProps extends PostData {
  onClick?: () => void;
}

export interface CommentData {
  id: number;
  author: string;
  avatar: string;
  text: string;
  timestamp: string;
}

// Enhanced SmartReview System Types
export enum BusinessCategory {
  RESTAURANT = 'restaurant',
  HOTEL = 'hotel',
  RETAIL = 'retail',
  SERVICE = 'service',
  ENTERTAINMENT = 'entertainment'
}

export interface StarRatingProps {
  value: number;
  onChange: (rating: number) => void;
  size?: 'small' | 'medium' | 'large' | 'compact';
  readonly?: boolean;
  showText?: boolean;
  maxRating?: number;
  allowHalfStars?: boolean;
  xiaomiStyle?: boolean;
  className?: string;
}

export interface DetailedRatingsProps {
  overallRating: number;
  detailedRatings: {
    quality: number;
    environment: number;
    service: number;
  };
  businessCategory: BusinessCategory;
  onOverallRatingChange: (rating: number) => void;
  onDetailedRatingChange: (type: 'quality' | 'environment' | 'service', rating: number) => void;
  readonly?: boolean;
  className?: string;
}

export interface CombinedRatingProps {
  overallRating: number;
  detailedRatings: {
    quality: number;
    environment: number;
    service: number;
  };
  businessCategory?: BusinessCategory;
  onOverallRatingChange: (rating: number) => void;
  onDetailedRatingChange: (type: 'quality' | 'environment' | 'service', rating: number) => void;
  readonly?: boolean;
  className?: string;
}

export interface ReviewData {
  id: string;
  merchantId: string;
  venueId: string;
  userId: string;
  overallRating: number;
  detailedRatings: {
    quality: number;
    environment: number;
    service: number;
  };
  reviewText: string;
  images: UploadedImage[];
  priceInfo: {
    amount: number;
    currency: string;
    type: 'per_person' | 'per_night' | 'total';
  };
  visitDate: Date;
  isAnonymous: boolean;
  syncToFeed: boolean;
  locationVerified: boolean;
  aiAssisted: boolean;
  aiSuggestions?: string[]; // New: Store AI suggestions used
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
  // Security & Moderation
  moderationStatus: ModerationStatus;
  contentFlags: ContentFlag[];
  characterCount: number;
  pointsEarned?: number; // For 20+ character incentive
}

export interface UploadedImage {
  id: string;
  file: File;
  url: string;          // Local blob URL for preview
  fileUrl?: string;     // R2 CDN URL after upload
  thumbnail: string;
  type: 'image' | 'video';
  // Enhanced upload state management
  uploadState: UploadState;
  compressionRatio?: number;
  originalSize: number;
  compressedSize: number;
  uploadProgress: number; // 0-100
  analysisResults?: ImageAnalysis;
  suggestedTags?: string[];
  // Security scanning
  piiDetected?: boolean;
  piiWarnings?: string[];
}

export interface UploadState {
  status: 'pending' | 'compressing' | 'uploading' | 'analyzing' | 'complete' | 'error';
  progress: number;
  error?: string;
  retryCount: number;
}

export interface ImageAnalysis {
  category: 'menu' | 'storefront' | 'food' | 'interior' | 'receipt' | 'other';
  confidence: number;
  detectedObjects: string[];
  suggestedHashtags: string[];
  // PII Detection
  containsPII: boolean;
  piiTypes: ('phone' | 'email' | 'address' | 'id_number')[];
  piiConfidence: number;
}

export interface DraftData extends Partial<ReviewData> {
  draftId: string;
  lastSaved: Date;
  merchantInfo: {
    id: string;
    name: string;
    category: BusinessCategory;
  };
  // Enhanced draft state
  autoSaveEnabled: boolean;
  syncStatus: 'local' | 'syncing' | 'synced' | 'conflict';
  version: number;
}

// Security & Moderation Models
export interface ModerationStatus {
  status: 'pending' | 'approved' | 'flagged' | 'rejected';
  reviewedAt?: Date;
  reviewedBy?: 'ai' | 'human';
  flags: ContentFlag[];
}

export interface ContentFlag {
  type: 'inappropriate' | 'spam' | 'fake' | 'pii' | 'sensitive';
  confidence: number;
  description: string;
  autoGenerated: boolean;
}

// Character Count & Incentive
export interface TextValidation {
  characterCount: number;
  wordCount: number;
  isMinimumMet: boolean; // 15 characters minimum
  isIncentiveEligible: boolean; // 20+ characters for points
  maxCharactersReached: boolean; // 200 character limit
  pointsToEarn: number;
}

// Smart Hints
export interface SmartHint {
  id: string;
  text: string;
  category: 'positive' | 'negative' | 'neutral';
  ratingRange: [number, number];
  businessCategories: BusinessCategory[];
  hashtag: string;
  // Character count integration
  characterContribution: number;
  pointsValue: number;
}

// Location Verification
export interface LocationVerification {
  isVerified: boolean;
  accuracy: number;
  timestamp: Date;
  coordinates: {
    latitude: number;
    longitude: number;
  };
}

// AI Streaming Models
export interface AIStreamingState {
  isStreaming: boolean;
  currentChunk: string;
  accumulatedText: string;
  error: string | null;
  progress: number; // 0-100
}

// AI Assistant State (New for Gemini Integration)
export interface AIAssistantState {
  isGenerating: boolean;
  suggestions: string[];
  currentSuggestion: string;
  error: string | null;
  isVisible: boolean;
}

export interface AIStreamingRequest {
  prompt: string;
  context: {
    rating: number;
    category: BusinessCategory;
    images: string[]; // Image analysis results
    currentText: string;
  };
  streamingOptions: {
    maxTokens: number;
    temperature: number;
    stopSequences: string[];
  };
}

export interface AIStreamingResponse {
  chunk: string;
  isComplete: boolean;
  totalTokens?: number;
  finishReason?: 'stop' | 'length' | 'content_filter';
  error?: string;
}

// Content Moderation Models
export interface ModerationRequest {
  text: string;
  images?: string[];
  userId: string;
  merchantId: string;
}

export interface ModerationResponse {
  approved: boolean;
  flags: ContentFlag[];
  suggestedEdits?: string[];
  severity: 'low' | 'medium' | 'high';
  requiresHumanReview: boolean;
}

// Image Compression Models
export interface CompressionOptions {
  maxWidth: number;
  maxHeight: number;
  quality: number; // 0.1 - 1.0
  maxSizeKB: number;
}

export interface CompressionResult {
  originalFile: File;
  compressedFile: File;
  originalSize: number;
  compressedSize: number;
  compressionRatio: number;
  quality: number;
  dimensions: {
    original: { width: number; height: number };
    compressed: { width: number; height: number };
  };
}

// State Management Types
export interface ValidationErrors {
  rating?: string;
  text?: string;
  images?: string;
  price?: string;
  general?: string;
}

export interface ReviewContextState {
  reviewData: Partial<ReviewData>;
  draftState: DraftState;
  uploadState: UploadState;
  aiState: AIStreamingState;
  aiAssistantState: AIAssistantState; // New: AI Assistant state
  validationErrors: ValidationErrors;
  isSubmitting: boolean;
  submitError?: string;
  draftNotice?: string;
}

export interface DraftState {
  currentDraft: DraftData | null;
  isAutoSaving: boolean;
  lastSaved: Date | null;
  hasUnsavedChanges: boolean;
}

export interface ReviewContextActions {
  updateRating: (rating: number) => void;
  updateDetailedRating: (type: 'quality' | 'environment' | 'service', rating: number) => void;
  updateText: (text: string) => void;
  addImage: (image: File) => void;
  removeImage: (imageId: string) => void;
  updateImageOrder: (imageIds: string[]) => void;
  updateImages: (images: UploadedImage[]) => void;
  streamAIText: (prompt: string) => void;
  saveDraft: () => void;
  loadDraft: (draftId: string) => void;
  validateForm: () => void;
  updatePriceInfo: (priceInfo: Partial<ReviewData['priceInfo']>) => void;
  updateSettings: (settings: { isAnonymous?: boolean; syncToFeed?: boolean }) => void;
  addTag: (tag: string) => void;
  removeTag: (tag: string) => void;
  reset: () => void;
  // New AI Assistant Actions
  generateAISuggestions: (request: import('../services/gemini').AIAssistRequest) => Promise<void>;
  selectAISuggestion: (suggestion: string) => void;
  toggleAIAssistant: () => void;
  clearAISuggestions: () => void;
  // New Upload & Submit Actions
  retryImage: (imageId: string) => Promise<boolean>;
  uploadImages: () => Promise<boolean>;
  submitReview: () => Promise<boolean>;
  setUploadError: (message: string) => void;
  clearUploadError: () => void;
  clearSubmitError: () => void;
  clearDraftNotice: () => void;
}

// Legacy compatibility
export interface WriteReviewFormData {
  restaurantName: string;
  rating: number;
  reviewText: string;
  image?: string;
}
