export const PATHS = {
    AUTH: {
        LOGIN: '/login',
        REGISTER: '/register',
        FORGOT_PASSWORD: '/forgot-password',
        GOOGLE_CALLBACK: '/auth/callback',
    },
    CUSTOMER: {
        ROOT: '/customer',
        HOME: '/customer/home',
        DISCOVER: '/customer/discover',
        ME: {
            ROOT: '/customer/me',
            PROFILE: '/customer/me/profile',
            EDIT_PROFILE: '/customer/me/edit-profile',
            SETTINGS: '/customer/me/settings',
            REVIEWS: '/customer/me/reviews',
            COMMUNITY: '/customer/me/community',
            PAYMENTS: '/customer/me/payments',
            PRIVACY: '/customer/me/privacy',
            NOTIFICATIONS: '/customer/me/notifications',
            HELP: '/customer/me/help',
        },
        POST: (id: string) => `/customer/post/${id}`,
        POST_DETAIL: '/customer/post/:id',
        WRITE_REVIEW: '/customer/write-review',
        WRITE_REVIEW_SELECT: '/customer/write-review/select',
        REVIEW_SUCCESS: '/customer/review-success',
        EXPLORE: '/customer/explore',
        MERCHANT_INFO: (id: string) => `/customer/merchant/${id}`,
        MERCHANT_DETAIL: '/customer/merchant/:id',
        MERCHANT_PROFILE_COUPON: (id: string) => `/customer/merchant/${id}/coupon`,
        MERCHANT_PROFILE_COUPON_DETAIL: '/customer/merchant/:id/coupon',
        MERCHANT_DEAL_QR: (id: string) => `/customer/merchant/${id}/deal-qr`,
        MERCHANT_DEAL_QR_DETAIL: '/customer/merchant/:id/deal-qr',
        VOUCHERS: '/customer/vouchers',
    },
    MERCHANT: {
        ROOT: '/merchant',
        LOGIN: '/merchant/login',
        VERIFICATION: '/merchant/verification',
        DASHBOARD: '/merchant/dashboard',
        ANALYTICS: '/merchant/analytics',
        ADS: '/merchant/ads',
        PROFILE: '/merchant/profile',
        CREATE_POST: '/merchant/create-post',
        MESSAGES: '/merchant/messages',
        CHAT_DETAIL: '/merchant/messages/:chatId',
        CHAT: (chatId: string) => `/merchant/messages/${chatId}`,
        CHAT_SEARCH: '/merchant/messages/:chatId/search',
        SEARCH_MESSAGES: (chatId: string) => `/merchant/messages/${chatId}/search`,
        NOTIFICATIONS: '/merchant/notifications',
    }
};
