export const PATHS = {
    AUTH: {
        LOGIN: '/login',
        REGISTER: '/register',
        FORGOT_PASSWORD: '/forgot-password',
        GOOGLE_CALLBACK: '/auth/callback/google',
    },
    CUSTOMER: {
        ROOT: '/customer',
        HOME: '/customer/home',
        DISCOVER: '/customer/discover',
        ME: {
            ROOT: '/customer/me',
            PROFILE: '/customer/me/profile',
            EDIT_PROFILE: '/customer/me/edit-profile',
            SETTINGS: '/customer/me/settings',
            REVIEWS: '/customer/me/reviews',
            COMMUNITY: '/customer/me/community',
            PAYMENTS: '/customer/me/payments',
            PRIVACY: '/customer/me/privacy',
            NOTIFICATIONS: '/customer/me/notifications',
            HELP: '/customer/me/help',
        },
        POST: (id: string) => `/customer/post/${id}`,
        POST_DETAIL: '/customer/post/:id',
        WRITE_REVIEW: '/customer/write-review',
        EXPLORE: '/customer/explore',
        VOUCHERS: '/customer/vouchers',
    },
    MERCHANT: {
        ROOT: '/merchant',
        LOGIN: '/merchant/login',
        DASHBOARD: '/merchant/dashboard',
        ADS: '/merchant/ads',
        PROFILE: '/merchant/profile',
        MESSAGES: '/merchant/messages',
        CHAT_DETAIL: '/merchant/messages/:chatId',
        CHAT: (chatId: string) => `/merchant/messages/${chatId}`,
        CHAT_SEARCH: '/merchant/messages/:chatId/search',
        SEARCH_MESSAGES: (chatId: string) => `/merchant/messages/${chatId}/search`,
        NOTIFICATIONS: '/merchant/notifications',
    }
};
